### ISSUE TITLE
Dind container doesn't support adding `extraEnv`

### ISSUE THREAD

**Issue by romogo17** [spacelift-io/spacelift-workerpool-k8s#17]
Hi team,

## Issue
Presently it's possible to add additional environment variables to the launcher container through the use of `extraEnv`

https://github.com/spacelift-io/spacelift-workerpool-k8s/blob/34ba079a0855c770d6e32be88e6668d41c822cd7/templates/deployment.yaml#L80-L82

However, this option doesn't seem to be available for the dind container

https://github.com/spacelift-io/spacelift-workerpool-k8s/blob/34ba079a0855c770d6e32be88e6668d41c822cd7/templates/deployment.yaml#L107-L109

This means that, for environments that are behind a proxy, it's only possible to configure the proxy for the launcher, making it so that the dind container cannot pull images from the internet
https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

## Proposed Solution
Add the `extraEnv` setting to the dind container 

## Alternate solutions
- Have customers build a custom dind image but this seems overkill if the configuration can be done through an environment variable
- Use a post renderer with a patch

**Comment by adamconnelly** [comment]
Thanks a lot @romogo17. Makes perfect sense, and your PR looks great.
